name: EntryTracker-ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  PUBLIC_ECR: public.ecr.aws/p2o8u9e5
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies and run the app
        run: |
          pip install --no-cache-dir -r requirements.txt
          python app.py &
          sleep 5
      - name: unit test
        run: |
          STATUS="$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)"
          if [ "$STATUS" = "200" ]; then
            echo "Application is up!"
          else
            echo "Application returned $STATUS"
            exit 1
          fi
      - name: Build image
        run: docker build -t entrytracker:latest .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin public.ecr.aws
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Tag image
        run: docker tag entrytracker:latest $PUBLIC_ECR/development/entrytracker:latest
      - name: Push image
        run: docker push $PUBLIC_ECR/development/entrytracker:latest
      
  E2E:
    runs-on: ubuntu-latest
    needs: builder
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose up &
          sleep 30
      - name: E2E test
        run: |
          STATUS="$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80)"
          if [ "$STATUS" = "200" ]; then
            echo "Application is up!"
          else
            echo "Application returned $STATUS"
            exit 1
          fi
  Deploy:
    runs-on: ubuntu-latest
    needs: E2E
    steps:
      - name: SSH to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            cd EntryTracker || git clone https://github.com/shakeddukeman25/AWS-EntryTracker.git EntryTracker && cd EntryTracker
            git pull origin main
            sudo docker rm -f mysql-db || true
            sudo docker compose down -v || true
            sudo docker compose pull
            sudo docker compose up -d --force-recreate
      - name: verify
        run: |
          STATUS="$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.EC2_HOST }})"
          if [ "$STATUS" = "200" ]; then
            echo "Application is up!"
          else
            echo "Application returned $STATUS"
            exit 1
          fi